mode: dev
data:
  dev_paths: ['data/libri_dev/data_list_sorted.json']
  text:
    mode: character
    vocab: data/libri_train_1h/vocab_char.txt

decode:
  type: greedy

hparam:
  val_batch_size: 4
  njobs: 4
  pin_memory: true

trainer:
  gpus: 1
  logger: false
  default_root_dir: model/transformer_trans
  deterministic: true
