checkpoint_callbacks:
  mode: min
  monitor: val_wer
  save_top_k: 5
ckpt: none
config: ../egs/librispeech/config/con_ctc.yaml
cpu: false
data:
  dev_paths:
  - data/libri_dev/data_list_sorted.json
  text:
    mode: character
    vocab: data/libri_train_1h/vocab_char.txt
  train_paths:
  - data/libri_train_1h/data_list_sorted.json
  - data/libri_train_9h/data_list_sorted.json
detect_anomaly: false
hparam:
  accum_grad: 4
  grad_clip: 5
  njobs: 4
  pin_memory: true
  train_batch_size: 8
  val_batch_size: 8
log_file: none
log_level: INFO
mode: train
model:
  encoder:
    attn_dropout: 0.2
    conv_dropout: 0.0
    conv_expansion_factor: 2
    conv_kernel_size: 31
    dim: 128
    ff_dropout: 0.2
    ff_mult: 4
  extractor:
    feature: hidden_states
    name: fbank
    train: false
  name: con_asr
  optim:
    algo: Adam
    kwargs:
      lr: 0.0002
  specaugment:
    freq_mask_num: 2
    freq_mask_range:
    - 0
    - 20
    time_mask_max: 1.0
    time_mask_num: 2
    time_mask_range:
    - 0
    - 40
    time_warp_w: 80
njobs: 2
override: ''
seed: 7122
test: false
test_name: test_result
trainer:
  check_val_every_n_epoch: 5
  default_root_dir: model/con_libri-10h_char
  deterministic: true
  flush_logs_every_n_steps: 5
  gpus: 1
  log_every_n_steps: 5
  logger: true
  max_epochs: 500
  max_steps: 100000
  precision: 16
